version: "3"
services:

  mssql:
    build:
      context: ./src/db/build
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - "leaf-mssql:/var/opt/mssql"
    #networks:
    #  local:
    #    aliases:
    #      - mssql
  
  coreapi:
    build: 
      context: ./src/server
    ports:
      - "5001:5001"
    depends_on:
      - mssql
    volumes:
      - ${KEYS}:/.keys
      - ${SERILOG_DIR}:/logs
    environment:
      LEAF_JWT_KEY_PW: ${LEAF_JWT_KEY_PW}
      LEAF_APP_DB: ${LEAF_APP_DB}
      LEAF_CLIN_DB: ${LEAF_CLIN_DB}
      SERILOG_DIR: /logs
    #networks:
    #  local:
    #    aliases:
    #      - coreapi

  #node:
  #  build: ./src/ui-client
  #  ports:
  #    - "3000:3000"
  #  depends_on:
  #    - mssql
  #    - coreapi
  #  volumes:
  #    - ./src/ui-client:/app
  #  #environment:
  #    #NODE_ENV: ${ENV_DOCKER_ENVIRONMENT}
  #  working_dir: /app
  #  command: ["npm", "start"]
  #  networks:
  #    local:
  #      aliases:
  #        - node

volumes:
  leaf-mssql:

#networks:
#  local:
#    driver: bridge
